[Discord]

DiscordToken = ""
ChannelTopicPrefix = "dcuncltr: "
ChannelCategoryName = "teamspeak channels"
ChannelTextPrefix = "uncltr-"

OptReaction = "🖕"
OptReactionCommand = "cmd::opt+in:out"

CleanChannelsOnStartup = true
MayflyCheckInterval = "1s"

DiscordGameStatus = "Issues  👉 github.com/darmiel/discord-unclutterer"

[Database]
AllowGhostPingBlocking = true
GhostPingBlockDefault = false
DatabaseBucketName = "ghostping-opt-out"
DatabasePath = "data.db"

[Cooldown]
OptCooldown = "2s"
JoinLeaveCooldown = "50s"
WarnViolationThreshold = 1

[Messages]
#Placeholders:
# * UserID
# * ChannelID
# * GuildID
# * ReactionCommand
# * OptReaction
# * VoiceChannelName
# * VoiceChannelID

ChannelCreateMessage = """
{{ ReactionCommand }}
Hallo! [ https://i.imgur.com/aHX3n0z.png ]

Dieser Channel wurde für den Voice-Channel `{{ VoiceChannelName }}` erstellt.
Er wird nur dann sichtbar, wenn du in diesen Voice-Channel gehst. (Privater Textkanal für Sprachkanäle).

Jedes Mal, wenn du Zugriff zu einem solchen Text-Channel bekommst, erhältst du einen Ghost-Ping.
Möchtest du diese Ghost-Pings nicht mehr erhalten, reagiere auf diese Nachricht mit '{{ OptReaction }}'`
"""

OptDisabled = "[ <@{{ UserID }}> | https://tenor.com/PXYQ.gif ] 🖕 😊 opting-in/out is disabled"

OptInLoading = "[ <@{{ UserID }}> ] 👈 **Opt-In** Ghost-Pings ... (loading)"
OptInErrorData = "[ <@{{ UserID }}> ] 👈 😡 **Nope:** {{ Error }}"
OptInSuccess = "[ <@{{ UserID }}> | https://tenor.com/v4hv.gif ] 👈 😊 Okay! Du erhältst wieder Ghost-Pings"

OptOutLoading = "[ <@{{ UserID }} ] 👉 **Opt-Out** Ghost-Pings ... (loading)"
OptOutErrorDatabase = "[ <@{{ UserID }}> ] 👉 😡 **Nope:** {{ Error }}"
OptOutSuccess = "[ <@{{ UserID }}> | https://tenor.com/wroQ.gif ] 👉 🖕 Okay! Du erhältst keine weiteren Ghost-Pings"


[Logging]
VerbosityLevel = 2 # 0 = none, 1 = error receiving channel, 2 = same channel
LogChat = true
LogUserJoin = true
LogUserLeave = true
LogCooldown = true
LogExcessiveCooldownViolations = true

LogOptOutError = true
LogOptInError = true

LogOptOutSuccess = true
LogOptInSuccess = true

LogCategoryCreate = true
LogChannelCreate = true

# todo: permissions config